# fly.toml app configuration file generated for reactivities2023 on 2023-06-23T12:09:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities2023"
primary_region = "ams"

[build]
  image = "arbov/reactivities_endava22"
  
[env]
ASPNETCORE_URLS="http://+:8080"
Cloudinary__Cloudname="reactivities-endava"
Cloudinary__ApiKey="115652428993828"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
